# Generated by Django 3.0.9 on 2023-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_email_notified',
            field=models.BooleanField(default=False),
        ),
    ]
